<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Info;
/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends \Doctrine\ORM\EntityRepository
{
		 /**
  *Nombre de synchro effectue par utilisateur 
  */
  public function findMeOnThis(Info $info){
         $qb = $this->createQueryBuilder('a')
         ->where('a.info=:info')->setParameter('info',$info);
          return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
  }
}
