<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceRepository extends EntityRepository
{

 public function findByVehicule($vehicule,$systeme)
{
  $qb = $this->createQueryBuilder('r')
  ->where('r.systeme=:systeme')
  ->andWhere('r.vehicule=:vehicule')
  ->setParameter('systeme', $systeme)
  ->setParameter('vehicule', $vehicule); 
   $qb->orderBy('r.dateSave', 'DESC');   
 return $qb->getQuery()->getResult();

}
}
