<?php

namespace AppBundle\Repository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends \Doctrine\ORM\EntityRepository
{

 public function findBySysteme($systeme)
{
  $qb = $this->createQueryBuilder('r')
  ->where('r.systeme=:systeme')
  ->setParameter('systeme', $systeme);   
 return $qb->getQuery()->getResult();

}	
}
