<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoliceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliceRepository extends EntityRepository
{
     public function findLastByVehicule($vehicule)
{
  $qb = $this->createQueryBuilder('r')
  ->where('r.vehicule=:vehicule')
  ->setParameter('vehicule', $vehicule)
  ->orderBy('r.startDate', 'DESC')
  ->setMaxResults(1); 
 return $qb->getQuery()->getOneOrNullResult();

}    
}
