<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoliceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliceRepository extends EntityRepository
{
     public function findLastByVehicule($vehicule)
{
  $qb = $this->createQueryBuilder('r')
  ->where('r.vehicule=:vehicule')
  ->setParameter('vehicule', $vehicule)
  ->orderBy('r.startDate', 'DESC')
  ->setMaxResults(1); 
 return $qb->getQuery()->getOneOrNullResult();

}  


 public function findCoutTotal($vehicule,$annee=false)
{

 $qb = $this->createQueryBuilder('v')
 ->andWhere('v.vehicule = :vehicule')
 ->setParameter('vehicule', $vehicule);
 if ($annee) {
 	$qb->andWhere('v.dateSave BETWEEN :debut AND :fin')
  ->setParameter('debut', new \Datetime(date('Y').'-01-01')) //
   ->setParameter('fin', new \Datetime(date('Y').'-12-31')); //
 }
 $qb->select('SUM(v.cout) as coutTotal');
       
 return $qb->getQuery()->getSingleScalarResult();
}
  


}
