<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends EntityRepository
{
 public function findByUser($user)
{
  $qb = $this->createQueryBuilder('p')
->where('p.info=:user')->setParameter('user', $user);   
   return $qb ->getQuery()->getResult();
  ;
}
   
}
