reparations:
    path:     /reparations/{idV}/{idO}/list
    defaults: { _controller: "AppBundle:Reparation:reparations" }
    methods:  GET

reparation_last:
    path:     /reparation/last
    defaults: { _controller: "AppBundle:Reparation:lastReparation" }
    methods:  GET

police_last:
    path:     /police/last
    defaults: { _controller: "AppBundle:Reparation:lastPolice" }
    methods:  GET

visite_last:
    path:     /visite/last
    defaults: { _controller: "AppBundle:Reparation:lastVisite" }
    methods:  GET

operation_todo:
    path:     /operation/todos
    defaults: { _controller: "AppBundle:Reparation:todos" }
    methods:  GET

is_todos:
    path:     /is/todos
    defaults: { _controller: "AppBundle:Reparation:isTodos" }
    methods:  GET

nedd_control:
    path:     /need/control
    defaults: { _controller: "AppBundle:Reparation:needControl" }
    methods:  GET

releve_last:
    path:     /releve/last
    defaults: { _controller: "AppBundle:Reparation:lastReleve" }
    methods:  GET
couts:
    path:     /couts
    defaults: { _controller: "AppBundle:Reparation:couts" }
    methods:  GET
    
maintenances:
    path:     /maintenances/list
    defaults: { _controller: "AppBundle:Reparation:maintenances" }
    methods:  [GET, POST]

reparation_create:
    path:     /reparation/create
    defaults: { _controller: "AppBundle:Reparation:createReparation" }
    methods:  [GET, POST]

maintenance_create:
    path:     /maintenance/create
    defaults: { _controller: "AppBundle:Reparation:createMaintenance" }
    methods:  [GET, POST]

releve_create:
    path:     /releve/create
    defaults: { _controller: "AppBundle:Reparation:createReleve" }
    methods:  [GET, POST]

police_create:
    path:     /police/create
    defaults: { _controller: "AppBundle:Reparation:createPolice" }
    methods:  [GET, POST]
visite_create:
    path:     /visite/create
    defaults: { _controller: "AppBundle:Reparation:createVisite" }
    methods:  [GET, POST]

reparation_update:
    path:     /reparation/{id}/update
    defaults: { _controller: "AppBundle:Reparation:updateReparation" }
    methods:  [GET, POST,PUT]

visite_update:
    path:     /visite/{id}/update
    defaults: { _controller: "AppBundle:Reparation:updateVisite" }
    methods:  [GET, POST,PUT]

police_update:
    path:     /police/{id}/update
    defaults: { _controller: "AppBundle:Reparation:updatePolice" }
    methods:  [GET, POST,PUT]

    
reparation_delete:
    path:     /reparation/{id}/delete
    defaults: { _controller: "AppBundle:Reparation:deleteReparation" }
    methods:  DELETE

maintance_delete:
    path:     /maintenance/{id}/delete
    defaults: { _controller: "AppBundle:Reparation:deleteMaintenance" }
    methods:  DELETE

police_delete:
    path:     /police/{id}/delete
    defaults: { _controller: "AppBundle:Reparation:deletePolice" }
    methods:  DELETE

visite_delete:
    path:     /visite/{id}/delete
    defaults: { _controller: "AppBundle:Reparation:deleteVisite" }
    methods:  DELETE

vehicule_index:
    path:     /vehicule
    defaults: { _controller: "AppBundle:Vehicule:index" }
    methods:  GET

vehicule_create:
    path:     /vehicule/create
    defaults: { _controller: "AppBundle:Vehicule:createVehicule" }
    methods:  [GET, POST]

vehicule_update:
    path:     /vehicule/{id}/update
    defaults: { _controller: "AppBundle:Vehicule:updateVehicule" }
    methods:  [GET, POST,PUT]

vehicule_delete:
    path:     /vehicule/{id}/delete
    defaults: { _controller: "AppBundle:Vehicule:deleteVehicule" }
    methods:  [DELETE,GET]

info_show_json:
    path:     /info/{uid}/show
    defaults: { _controller: "AppBundle:Info:showJson" }

abonnement_show_json:
    path:     /abonnement/{uid}/show
    defaults: { _controller: "AppBundle:Info:showAbonnement" }

info_update_json:
    path:     /info/{uid}/update
    defaults: { _controller: "AppBundle:Info:editJson" }