info_index:
    path:     /
    defaults: { _controller: "AppBundle:Info:index" }
    methods:  GET

info_show:
    path:     /{uid}/show
    defaults: { _controller: "AppBundle:Info:show" }
    methods:  GET

info_new:
    path:     /new
    defaults: { _controller: "AppBundle:Info:new" }
    methods:  [GET, POST]

info_edit:
    path:     /{uid}/edit
    defaults: { _controller: "AppBundle:Info:edit" }
    methods:  [GET, POST]

info_delete:
    path:     /{uid}/delete
    defaults: { _controller: "AppBundle:Info:delete" }
    methods:  DELETE
