AppBundle\Entity\Police:
    exclusion_policy: none
    properties:
        id:
            groups: ['full']
        startDate:
            groups: ['full']
            expose: true
            type: DateTime<'Y-m-d'>            
        endDate:
            groups: ['full'] 
            expose: true
            type: DateTime<'Y-m-d'>               
        cout:
            groups: ['full']        
        expired:
            groups: ['full']      