AppBundle\Entity\Reparation:
    exclusion_policy: none
    properties:
        id:
            groups: ['full']
        dateSave:
            groups: ['full']
        duree:
            groups: ['full']    
        cout:
            groups: ['full']        
        km:
            groups: ['full']       
        expired:
            groups: ['full'] 