AppBundle\Entity\Releve:
    exclusion_policy: none
    properties:
        id:
            groups: ['full']
        dateSave:
            groups: ['full']  
            expose: true
            type: DateTime<'Y-m-d'>                  
        km:
            groups: ['full']       
        expired:
            groups: ['full'] 