AppBundle\Entity\Abonnement:
    exclusion_policy: none
    properties:
        id:
            groups: ['full','info']
        startDate:
            groups: ['full','info']  
            expose: true
            type: DateTime<'Y-m-d'>   
        endDate:
            groups: ['full','info']  
            expose: true
            type: DateTime<'Y-m-d'>                             
        nbervehicule:
            groups: ['full','info']       
        status:
            groups: ['full','info']   
        info:
            groups: ['abonnement']   